name: React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint . --ext .ts,.tsx

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build
